[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ipydrop"
version = "0.0.1"
dependencies = ["anywidget"]
readme = "README.md"

[project.urls]
Homepage = "https://github.com/kolibril13/ipydrop"
Source = "https://github.com/kolibril13/ipydrop"
Tracker = "https://github.com/kolibril13/ipydrop/issues"

[tool.uv]
dev-dependencies = ["watchfiles", "jupyterlab"]

# automatically add the dev feature to the default env (e.g., hatch shell)
[tool.hatch.envs.default]
features = ["dev"]


[tool.hatch.build]
only-packages = true
artifacts = ["src/ipydrop/static/*"]

[tool.hatch.build.hooks.jupyter-builder]
build-function = "hatch_jupyter_builder.npm_builder"
ensured-targets = ["src/ipydrop/static/widget.js"]
skip-if-exists = ["src/ipydrop/static/widget.js"]
dependencies = ["hatch-jupyter-builder>=0.5.0"]

[tool.hatch.build.hooks.jupyter-builder.build-kwargs]
npm = "npm"
build_cmd = "build"
